### PR TITLE
Automatically advance to next question 

### PR DESCRIPTION
**Pull request by vegetabill**
* automatically advance to next question after showing the success message for 2 seconds

This is (part?) of issue #11. I didn't know if there should be success feedback beyond the text message or if we still want the button.

Let me know what your thoughts are.

=Bill

### CODE REVIEW

**Comment by deeptiGarg** [comment]
Could you please add a gif to this as well showing the changes in action. 

Yeah, we do not want the "Next Shortcut" button.
Flow is something like this: 

Question 1 comes -> User answers correctly -> "Correct Keys Pressed" printed -> Automatically move to next question (no explicit button).

**Comment by vegetabill** [comment]
Sorry for the delay. Working on this one again.

**Comment by deeptiGarg** [comment]
This one is already completed. I implemented it last week or before that.

**Comment by vegetabill** [comment]
Okay. Closing then.

**Pull request closed without merging**
