### PR TITLE
Remove unneeded files

### PR DESCRIPTION
**Pull request by mobasergio**

### CODE REVIEW

**Comment by arpi-r** [comment]
Changes look good!

If you edit your description to use one of the special keywords, it will automatically link the issue and make it easier for you to get credit for the PR.

> By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into main, it will also automatically close the issue.

**Review by tilaprimera — DISMISSED** [review]
Thanks @mobasergio Looks good!

**Comment by alodahl** [comment]
I assume there's no issue attached to this, but let me know quick before I merge.

**Comment by tilaprimera** [comment]
> 
> 
> I assume there's no issue attached to this, but let me know quick before I merge.
Yes, I didn't get an issue with this change.

**Comment by arpi-r** [comment]
This resolves issue #106

**Comment by alodahl** [comment]
fixes #106

**Pull request merged**
