### PR TITLE
added shortcut type tag to JSON object and main screen

### LINKED ISSUE #47: Disambiguate between mac keyboard shortcuts and shell shortcuts
I'd love to see some indication that the keyboard shortcut I'm on is for the mac operating system vs the shell.

Suggestion: add navigation between different sets of shortcuts, perhaps after we get shortcuts for more programs, #22

### PR DESCRIPTION
**Pull request by belebull**
## Changes
* added shortcut type property to JSON
* added tag to main screen

Screen Shot 2020-10-01 at 2 20 58 PM

## Related Issue
fixes #47

### CODE REVIEW

**Comment by vegetabill** [comment]
@belebull thanks for submitting this! We'll be reviewing it shorly.

GitHub tip: if you edit your description to use one  of the special keywords, it will automatically link the issue and make it easier for you to get credit for the PR.

> By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into main, it will also automatically close the issue.

**Comment by belebull** [comment]
> @belebull thanks for submitting this! We'll be reviewing it shorly.
> 
> GitHub tip: if you edit your description to use one of the special keywords, it will automatically link the issue and make it easier for you to get credit for the PR.
> 
> > By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into main, it will also automatically close the issue.

Thanks for letting me know!

**Review by alodahl — CHANGES_REQUESTED** [review]
The tag works, but are some of these shell shortcuts?  Like control+q, control+l, control+u, control+w?

**Comment by belebull** [comment]
> The tag works, but are some of these shell shortcuts? Like control+q, control+l, control+u, control+w?

Great catch - I was looking at the cheat sheet and didn't see some of the shell commands there. I'll make an update!

**Review by alodahl — CHANGES_REQUESTED** [review]
Would you mind making the shell v mac tags different colors?  I was focused on seeing it change and I almost didnt notice.

**Comment by belebull** [comment]
> Would you mind making the shell v mac tags different colors? I was focused on seeing it change and I almost didnt notice.

Let me know if this color change works!
Screen Shot 2020-10-01 at 5 26 44 PM

**Comment by alodahl** [comment]
I don't know what I'm doing wrong, but I'm no longer seeing any tags at all.

**Comment by belebull** [comment]
That's odd - I'm looking at my dev now and it looks fine even after reloading the page and restarting npm. Any suggestions on how to fix this?

**Review by alodahl — APPROVED** [review]
The colors look great. Id like someone else to look give their opinion about which ones are mac v shell.

**Comment by alodahl** [comment]
You can pick up something else while we're waiting =)

**Review by tilaprimera — APPROVED** [review]
First of all, it looks awesome. Verified the mac and shell shortcuts. On the color choices, may be nice to have would be if the keyboard keys' colors match the tag color.

**Comment by alodahl** [comment]
Whoa, great idea @tilaprimera , maybe we can make that into a new issue.

**Pull request merged**
