### PR TITLE
App can use Auth0 or local dev auth

### LINKED ISSUE #74: Create fake login/logout for local development
Auth0 is being integrated as part of #73 but we don't want to force all contributors to configure Auth0 just to work on the app so we'll have a simple auth setup for local development.

Feel free to suggest a better way to do this. This just one possible way among many.

- This should be the default way the app works unless Auth0 is setup - which will be done in #73 
- Add the [cookie-session](https://www.npmjs.com/package/cookie-session) package or your preferred cookie library
  - If you haven't worked directly with cookies before, read this [background doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)
- Implement a `GET /login` endpoint
  - It should set a cookie, `userId` which will just be the environment variable `USER` (your OS username) which has a lifetime of 1 hour
  - If no user record exists with that id, create it. Sequelize has a `findOrCreate` helper that makes this easy
  - The response to this endpoint should be a redirect to `/`
- Implement a `GET /logout` endpoint
  - It should unsets the cookie value
  - Response should be a redirect to `/`
- Update the `/user/progress` endpoint added in #66 so that the userId will be the logged-in user id if the cookie has the value set

If you have any question about cookies, Express, ping Bill D in Slack.

### PR DESCRIPTION
**Pull request by vegetabill**
Closes #74 - sorry for some of noisy diffs but the vscode setting for prettier only on modified lines wasn't working properly for me so the whole files got formatted 😬

Since I worked on a spike when we were creating the OSD tickets, it wasn't too much work to adapt it into a better-quality version for this PR.

- Configures either Auth0 or simple session, `/login` logs you in with user id of `process.env.USER`
- Will auto-create user record if needed so foreign key constraints will be met for future saves
- Protect API routes to need an authenticated user
- Fix some of the ORM models to take advantage of certain options and so they work in postgres

Tested fully using four combinations:
1. Auth0+postgres
1. dev+postgres
1. Auth0+sqlite
1. dev+sqlite

### CODE REVIEW

**Comment by alodahl** [comment]
Can you help me with some validation instructions, @vegetabill ?

**Comment by vegetabill** [comment]
Lol sure @alodahl sorry it's a bit of a complicated PR but hopefully makes dev itself simpler. If you start up with no `.env` file you should have the mock login working correctly, which means you can log in or out via the footer. And then, as a regression Auth0 config should still work and take precedence. Lmk if that gets you started!

**Comment by alodahl** [comment]
Sorry, I'm not amazing at backend... I'm seeing the login without .env, but I'm fighting with auth0 to use my own account, even though I'm pretty sure I have the right env variables now. I suppose I just have settings wrong, but then again, do you think we need more explicit directions for people developing this locally?

**Comment by alodahl** [comment]
https://dev-wxcenw7c.us.auth0.com/authorize

**Comment by alodahl** [comment]
Screen Shot 2020-10-24 at 11 45 21 AM

**Comment by alodahl** [comment]
You are welcome to merge this if you're certain it works locally, but I would love there to be a link or something in the readme for others who run into this error.

**Comment by vegetabill** [comment]
@alodahl thanks for checking it out.

What callback did you configure as the *Allowed Callback URLs* in the Auth0 UI? `http://localhost:3000/callback` is what it should be for the app. We can make that explicit in the instructions if you think that's necessary. If so let's open a new issue. In general part of the point of this PR is that anyone who doesn't understand Auth0 won't have to deal with it but it doesn't bode well if you couldn't get it working.

I fixed the conflicts and will merge this feature.

**Comment by vegetabill** [comment]
Actually I can't merge 😭 but it's ready

**Comment by alodahl** [comment]
Ah yes, I did not figure that out myself, but it works. Merging.

**Review by alodahl — APPROVED** [review]

**Pull request merged**
