### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by nidhishs**
Used serve-icon middleware to serve favicon.
Closes issue #93

### CODE REVIEW

**Review by alodahl — COMMENTED** [review]
Hello, I'm trying to validate, but I'm not seeing the favicon in Chrome or Safari.  Also, I don't think you should have to install anything to get a favicon to show up.

**Comment by nidhishs** [comment]
> Hello, I'm trying to validate, but I'm not seeing the favicon in Chrome or Safari.

In Safari,
image

In Chrome,
image

In Firefox,
image

Seems to be working perfectly fine for me. Maybe try clearing browser cache?

>Also, I don't think you should have to install anything to get a favicon to show up.

Trying to do it without a middleware by adding the following line in `app.js`, 
`app.use(express.favicon('./public/images/favicon.ico'));`

Returns the following error msg:
>Error: Most middleware (like favicon) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.

**Comment by alodahl** [comment]
I have cleared the cache.

**Comment by nidhishs** [comment]
> I have cleared the cache.

I'm not sure how we can replicate the issue. Could we get someone additional to review it as well?

**Comment by nidhishs** [comment]
> Hello, I'm trying to validate, but I'm not seeing the favicon in Chrome or Safari.

Is it working on other browsers such as Firefox or Edge?

**Comment by alodahl** [comment]
I tried it in browserstack and it seems to work 🤷🏻‍♀️
@vegetabill @MichelleGlauser what to you think?  Shall we merge?

Screen Shot 2020-10-11 at 12 20 35 PM

**Review by vegetabill — APPROVED** [review]
Awesome!

**Pull request merged**
