### PR TITLE
Add cross-env package for processing env variables in any platform

### LINKED ISSUE #100: Bug: npm start cannot work on Windows
Currently `npm start` runs `NODE_ENV=development nodemon` but that only works on unix/mac.

Please look into a cross-platform way to specify env variables, if one exists or a way to vary the script based on platform.

### PR DESCRIPTION
**Pull request by paulrrdiaz**
Close #100

### CODE REVIEW

**Comment by alodahl** [comment]
To validate on a PC or mac:

Enter this in your terminal: gh pr checkout 112
Run npm i && npm start
open localhost:3000
Everything should run as expected without errors.

**Review by alodahl — APPROVED** [review]
It works on mac.

**Review by Shraddha2104 — APPROVED** [review]
Works perfectly!

**Comment by alodahl** [comment]
On mac or PC @Shraddha2104 ?

**Comment by tilaprimera** [comment]
This results in "'NODE_ENV' is not recognized as an internal or external command" error on a windows machine. Were there any additional steps in terms of package install to ensure this works? @Shraddha2104 Oh did it work on Windows as well. It seems to be throwing error when I clone this repo, and test npm i, and npm start. 

>

**Comment by alodahl** [comment]
That happens when you follow these steps, @tilaprimera ? https://github.com/Techtonica/keyboard-shortcuts-practice/pull/112#issuecomment-702405716

**Comment by alodahl** [comment]
@paulrrdiaz do you know why this is happening for @tilaprimera ?

**Review by tilaprimera — COMMENTED** [review]
This results in NODE_ENV' is not recognized as an internal or external command error on a windows machine. Were there any additional steps in terms of package install to ensure this works? @Shraddha2104 Oh did it work on Windows as well. It throws the aforementioned error when I clone this repo, at the backend branch -- and run

npm i && npm start

**Comment by paulrrdiaz** [comment]
@alodahl I'm on windows, and everything works well 🤔

**Comment by alodahl** [comment]
@tilaprimera it wouldn't be the backend branch.  it would be on `gh pr checkout 112`

**Comment by tilaprimera** [comment]
> 
> 
> @tilaprimera it wouldn't be the backend branch. it would be on `gh pr checkout 112`
Looked into the right branch, it works perfectly.

**Comment by alodahl** [comment]
@tilaprimera do you approve, then?

**Comment by alodahl** [comment]
@paulrrdiaz  if you resolve your conflicts and we get a third approval, I'll merge.

**Pull request merged**
