### PR TITLE
Integrate all auth-dependent API stories into working app version

### LINKED ISSUE #77: Logging in will return user to the last question they were on
This is blocked by #66 and is to correctly implement the `/user/progress` placeholder endpoint.

Until #74 is implemented, you will need to set up Auth0 in order to know how is logged in.

We should lookup the most recently added answer data for a user and return its question number + 1 as the current number. We should use this as the authoritative source of the current question number, not local storage as it is now.

### PR DESCRIPTION
**Pull request by vegetabill**
This is a broad PR but it didn't really make sense to do piecemeal. After this merge, the various API's can be used together to save answers and resume progress. Since dev auth is working, it gets rid of localStorage and any hardcoded/dummy saving.

- This closes #77 since that was the placeholder to actually check progress.
- I disabled auto-formatting but I did remove commented-out cruft and added some variable declarations (let/const) while I was in some of the functions.
- Adds an integration API test that can be run to validate the API is working properly without using the app

### CODE REVIEW

**Review by alodahl — COMMENTED** [review]
Hey, I'm not sure why I would get unauthorized if these are just tests.  What do you think is happening?

```
keyboard-shortcuts-practice al$ npm i && npm run test
audited 488 packages in 1.587s

53 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> keyboard-shortcuts-practice@1.0.0 test /Users/al/projects/keyboard-shortcuts-practice
> npx jasmine

Using Auth0 auth
Randomized with seed 03112
Started
(node:36759) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
Executing (default): SELECT 1+1 AS result
Executing (default): SELECT 1+1 AS result
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`last_login` DATETIME, `id` VARCHAR(255) PRIMARY KEY, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL);
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`last_login` DATETIME, `id` VARCHAR(255) PRIMARY KEY, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
Executing (default): CREATE TABLE IF NOT EXISTS `user_answers` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `user_id` VARCHAR(255) NOT NULL REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `question_number` INTEGER NOT NULL, `is_correct` TINYINT(1) NOT NULL, `elapsed_time_ms` INTEGER NOT NULL, `created_at` DATETIME NOT NULL);
Executing (default): CREATE TABLE IF NOT EXISTS `user_answers` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `user_id` VARCHAR(255) NOT NULL REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `question_number` INTEGER NOT NULL, `is_correct` TINYINT(1) NOT NULL, `elapsed_time_ms` INTEGER NOT NULL, `created_at` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`user_answers`)
Executing (default): PRAGMA INDEX_LIST(`user_answers`)
Listening on http://localhost:3000 :-D
Executing (default): DELETE FROM `user_answers`
GET /user/progress 401 3.786 ms - 12
.Executing (default): DELETE FROM `user_answers`
GET /login 302 288.040 ms - 345
GET /user/progress 401 1.438 ms - 12
FExecuting (default): DELETE FROM `user_answers`
GET /login 302 2.193 ms - 345
POST /user/answers/question/7 401 11.541 ms - 12
POST /user/answers/question/7 401 1.074 ms - 12
POST /user/answers/question/7 401 1.004 ms - 12
POST /user/answers/question/7 401 0.899 ms - 12
GET /user/answers/question/7 401 0.826 ms - 12
FExecuting (default): DELETE FROM `user_answers`
GET /login 302 1.669 ms - 345
POST /user/answers/question/5 401 0.715 ms - 12
F

Failures:
1) User API when logged in should have default of first question
  Message:
    Error: expected 200 "OK", got 401 "Unauthorized"
  Stack:
    Error: expected 200 "OK", got 401 "Unauthorized"
        at Test._assertStatus (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:270:12)
        at Test._assertFunction (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:285:11)
        at Test.assert (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:175:21)
        at Server.localAssert (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:133:12)
        at Object.onceWrapper (events.js:427:28)
        at Server.emit (events.js:321:20)
        at emitCloseNT (net.js:1653:8)
        at processTicksAndRejections (internal/process/task_queues.js:83:21)

2) User API when logged in should return up to 3 previous question timings for a question
  Message:
    Error: expected 200 "OK", got 401 "Unauthorized"
  Stack:
    Error: expected 200 "OK", got 401 "Unauthorized"
        at Test._assertStatus (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:270:12)
        at Test._assertFunction (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:285:11)
        at Test.assert (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:175:21)
        at Server.localAssert (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:133:12)
        at Object.onceWrapper (events.js:427:28)
        at Server.emit (events.js:321:20)
        at emitCloseNT (net.js:1653:8)
        at processTicksAndRejections (internal/process/task_queues.js:83:21)

3) User API when logged in should update progress when an answer is saved
  Message:
    Error: expected 201 "Created", got 401 "Unauthorized"
  Stack:
    Error: expected 201 "Created", got 401 "Unauthorized"
        at Test._assertStatus (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:270:12)
        at Test._assertFunction (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:285:11)
        at Test.assert (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:175:21)
        at Server.localAssert (/Users/al/projects/keyboard-shortcuts-practice/node_modules/supertest/lib/test.js:133:12)
        at Object.onceWrapper (events.js:427:28)
        at Server.emit (events.js:321:20)
        at emitCloseNT (net.js:1653:8)
        at processTicksAndRejections (internal/process/task_queues.js:83:21)

4 specs, 3 failures
Finished in 0.385 seconds
Randomized with seed 03112 (jasmine --random=true --seed=03112)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keyboard-shortcuts-practice@1.0.0 test: `npx jasmine`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keyboard-shortcuts-practice@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by alodahl** [comment]
Login works up until the redirect:
Screen Shot 2020-11-15 at 2 09 22 PM

**Comment by vegetabill** [comment]
@alodahl thanks for verifying! IIRC this is related to not being SSL for localhost, as I've seen that throughout, but I wasn't exactly sure what exact conditions trigger it and when I refresh or try again it just seems to work 🤷‍♂️. Can you try the same steps on `backend` and see if it's a regression or not? If so, we can create a task to avoid the issue, although I hope enabling SSL isn't the only way to fix it.

**Comment by vegetabill** [comment]
@alodahl can you confirm that issue? I'm fairly certain it's just a general issue and not related to this PR.

**Review by alodahl — APPROVED** [review]
I don't suppose that makes any sense since there are not tests in `backend` yet, so lets just merge and move forward from there.

**Pull request merged**
