### PR TITLE
34  caps lock toggle

### PR DESCRIPTION
**Pull request by ashley-g**
Previously we were trying to handle any press of the caps lock as a key down event in the handle function. I learned that turning caps lock on is a key down event, but turning caps lock off is a key up event. So I have fixed this so turning caps lock on is handled in the handle function and turning caps lock off is handled in the release function. I have also removed the portion of code in the handle function that was previously trying to handle the caps lock off since it is unreachable.

### CODE REVIEW

**Review by alodahl — APPROVED** [review]

**Comment by alodahl** [comment]
I'd like one more approval, and then we can merge.

**Comment by alodahl** [comment]
Next reviewer:  Aside from the code, you can test how the caps lock key behaves

Before: https://techtonica.github.io/keyboard-shortcuts-practice/

After: 
- Enter this in your terminal: `gh pr checkout 98`
- Run `npm i && npm start`
- open localhost:3000
- test the caps lock key behavior again

**Review by vegetabill — APPROVED** [review]
Ahh thanks nice fix and explanation!

**Review by Shraddha2104 — APPROVED** [review]
This is awesome!! Nice fix @ashley-g 
Submit your PR here -https://forms.gle/E7nYZ2yKMNDo7iZc9 to win an Amazon gift card!

**Comment by tilaprimera** [comment]
On Windows, it throws a 'NODE_ENV'  is not recognized as an internal or external command error.

**Comment by alodahl** [comment]
Closes #34

**Pull request merged**
